### ISSUE TITLE
오류수정

### ISSUE THREAD

**Issue by GaEunJang** [ossteamgejs/Teamproject#10]
product.c:148:17: warning: format ‘%s’ expects argument of type ‘char *’, but argument 2 has type ‘char (*)[20]’ [-Wformat=]
         scanf("%s", &search);
                ~^   ~~~~~~~
product.c: In function ‘main’:
product.c:275:1: error: expected declaration or statement at end of input
 }

이 부분에 오류가 있는 것 같습니다!

**Comment by limjaeseong** [comment]
확인해보겠습니다!
