### ISSUE TITLE
오류수정 2

### ISSUE THREAD

**Issue by GaEunJang** [ossteamgejs/Teamproject#12]
product.c:82:2: warning: data definition has no type or storage class
  fclose(fp);
  ^~~~~~
product.c:82:2: warning: type defaults to ‘int’ in declaration of ‘fclose’ [-Wimplicit-int]
product.c:82:2: warning: parameter names (without types) in function declaration
product.c:83:9: error: expected declaration specifiers or ‘...’ before string constant
  printf("저장됨!\n");
         ^~~~~~~~~~~~~~
product.c:84:1: error: expected identifier or ‘(’ before ‘}’ token
 }
 ^
product.c: In function ‘loadData’:
product.c:98:45: warning: format ‘%[^,’ expects argument of type ‘char *’, but argument 6 has type ‘char (*)[20]’ [-Wformat=]
        sscanf(line,"%[^,], %[^,], %[^,], %[^,] %[^,], %d",s[count].name,s[count].explain,s[count].weight,&s[count].date,& s[count].category,&s[count].price);   }
                                          ~~~^                                                            ~~~~~~~~~~~~~~
product.c:98:51: warning: format ‘%[^,’ expects argument of type ‘char *’, but argument 7 has type ‘char (*)[30]’ [-Wformat=]
        sscanf(line,"%[^,], %[^,], %[^,], %[^,] %[^,], %d",s[count].name,s[count].explain,s[count].weight,&s[count].date,& s[count].category,&s[count].price);   }


이렇게 오류가 있습니다!

**Comment by limjaeseong** [comment]
확인해보겠습니다!

**Comment by GaEunJang** [comment]
product.c: In function ‘loadData’:
product.c:97:45: warning: format ‘%[^,’ expects argument of type ‘char *’, but argument 6 has type ‘char (*)[20]’ [-Wformat=]
        sscanf(line,"%[^,], %[^,], %[^,], %[^,] %[^,], %d",s[count].name,s[count].explain,s[count].weight,&s[count].date,& s[count].category,&s[count].price);   }
                                          ~~~^                                                            ~~~~~~~~~~~~~~
product.c:97:51: warning: format ‘%[^,’ expects argument of type ‘char *’, but argument 7 has type ‘char (*)[30]’ [-Wformat=]
        sscanf(line,"%[^,], %[^,], %[^,], %[^,] %[^,], %d",s[count].name,s[count].explain,s[count].weight,&s[count].date,& s[count].category,&s[count].price);   }

몇개는 해결했습니다!
나머지 확인해주세요

**Comment by limjaeseong** [comment]
category랑 date앞에 있는 %를 빼면 해결될 것 같습니다!

**Comment by GaEunJang** [comment]
네! 해결됐습니다
