### ISSUE TITLE
함수 설계

### ISSUE THREAD

**Issue by limjaeseong** [ossteamgejs/Teamproject#2]

**Comment by GaEunJang** [comment]
추가, 수정 , 삭제, 읽기 , 데이터 파일 저장/ 읽어오기 외에 
검색 기능 4가지 정도로 접근하는게 어떨까요?

**Comment by limjaeseong** [comment]
좋은거 같아요. 함수 정의 전에 구조체를 먼저 정해볼까요?

**Comment by GaEunJang** [comment]
네 좋아요!
품목 이름, 품목 가격, 품목 설명, 품목 무게, 유통기한 이 정도로 생각해보았는데 더 다른 생각 있으면 말해주세요!

**Comment by limjaeseong** [comment]
카테고리도 추가하면 좋을 것 같아요!

**Comment by GaEunJang** [comment]
그러면 이름 검색 기능, 품목 가격 검색 기능, 품목 무게 검색 기능, 카테고리 검색 기능 이렇게 4개 어떤가요?

**Comment by limjaeseong** [comment]
품목 무게 검색 기능말고 품목 설명 검색 기능으로 하는게 더 좋아보여요!

**Comment by GaEunJang** [comment]
좋아요 그럼 그렇게 10개의 기능으로 설계하는 것으로 해요!
