### ISSUE TITLE
나머지 함수 구현

### ISSUE THREAD

**Issue by limjaeseong** [ossteamgejs/Teamproject#8]
파일 저장 및 불러오기 함수와 검색 기능을 가진 4개의 함수를 어떻게 나눌까요?

**Comment by GaEunJang** [comment]
제가 제품 이름 검색 함수, 제품 중량 검색 함수, 파일 저장 함수 구현할게요! 
재성님이 카테고리 검색 함수, 가격 검색 함수, 불러오기 함수 구현 하실래요!?

**Comment by limjaeseong** [comment]
좋아요!

**Comment by GaEunJang** [comment]
다 구현 했습니다. 확인해주세요!

**Comment by limjaeseong** [comment]
저도 구현 완료했습니다.
